### ISSUE TITLE
SaveOnBestTrainingRewardCallback

### ISSUE THREAD

**Issue by liuliuliuzj11** [llach/tiago_rl#2]
Hi,
when running learn_closing.py I get this error.
ImportError: cannot import name 'SaveOnBestTrainingRewardCallback' from 'tiago_rl.misc'
Thank you.

**Comment by llach** [comment]
Hi, 
did you follow the installation instructions, in particular, did you run `pip install -e .` in the repository folder?

Also, please note that this repo is outdated. The new version of the TIAGo RL environments for grasping are here: https://github.com/llach/learning_fc

**Comment by liuliuliuzj11** [comment]
Thanks for your reply! I will try to install the new TIAGo RL environments for grasping.

**Comment by llach** [comment]
Sure thing!
